// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgcflulkrzpxjijecebp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnY2ZsdWxrcnpweGppamVjZWJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDU1ODMsImV4cCI6MjA2NTQ4MTU4M30.nrLsZcwGPHcHSGUaAgVWr2qjUxESDepOLAVTijbKP7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);